# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20161104_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('origin', models.CharField(max_length=255)),
                ('destiny', models.CharField(max_length=255)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Bus')),
            ],
        ),
        migrations.RemoveField(
            model_name='buslocationpings',
            name='bus',
        ),
        migrations.AddField(
            model_name='buslocationpings',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='management.BusRoute'),
            preserve_default=False,
        ),
    ]
