# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20161104_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
