# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_routeendpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='destiny',
        ),
        migrations.AddField(
            model_name='busroute',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='as_destination', to='management.RouteEndpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busroute',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_origin', to='management.RouteEndpoint'),
        ),
    ]
