# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20161104_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos'),
            preserve_default=False,
        ),
    ]
