# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_client_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='busroute',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='management.Bus'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='management.BusRoute'),
        ),
    ]
